cxx_library(
  name = "corort",
  headers = glob(["*.hpp"], exclude = ["*.test.hpp"]),
  srcs = glob(["*.cpp"], exclude = ["*.test.cpp"]),
  deps = ["//.buck/conan:asio", "//.buck/conan:fmt"],
  tests = [":ut"],
  visibility = ["PUBLIC"],
)

