cxx_library(
  name = "util",
  exported_headers = glob(["*.hpp"], exclude = ["*.test.hpp"]),
  srcs = glob(["*.cpp"], exclude = ["*.test.cpp"]),
  exported_deps = ["//.buck/contrib/conan:asio", "//.buck/contrib/conan:fmt"],
  tests = [":ut"],
  visibility = ["PUBLIC"],
)

cxx_test(
    name = "ut",
    srcs = glob(["*.test.cpp"]),
    headers = glob(["*.test.hpp"]),
    args = ["--rng-seed", "time"],
    link_style = "static",
    deps = [":util", "//.buck/contrib/conan:catch2-main"]
)
