find_package(PkgConfig QUIET)
pkg_check_modules(PC_WAYLAND_CLIENT QUIET wayland-client)

find_path(WAYLAND_CLIENT_INCLUDE_DIR
  NAMES wayland-client.h
  PATHS
    ${PC_WAYLAND_CLIENT_INCLUDEDIR}
    ${PC_WAYLAND_CLIENT_INCLUDE_DIRS}
  PATH_SUFFIXES wayland
)
find_library(WAYLAND_CLIENT_LIBRARY
  NAMES wayland-client
  PATHS ${PC_WAYLAND_CLIENT_LIBRARY_DIRS}
)
set(WAYlAND_VERSION ${PC_WAYLAND_CLIENT_VERSION})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Wayland
  REQUIRED_VARS
    WAYLAND_CLIENT_INCLUDE_DIR WAYLAND_CLIENT_LIBRARY
  VERSION_VAR WAYlAND_VERSION
)

mark_as_advanced(
  WAYLAND_CLIENT_INCLUDE_DIR
  WAYLAND_CLIENT_LIBRARY
)

if (WAYLAND_FOUND)
  add_library(Wayland::client UNKNOWN IMPORTED)
  set_target_properties(Wayland::client PROPERTIES
    IMPORTED_LOCATION "${WAYLAND_CLIENT_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${WAYLAND_CLIENT_INCLUDE_DIR}"
    INTERFACE_COMPILE_OPTIONS "${PC_WAYLAND_CLIENT_CFLAGS_OTHER}"
  )
endif()
